version: '2'

services:
  cakephp:
    container_name: php-apache
    build: .
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    volumes:
      - ./htdocs:/var/www/html
    environment:
      - SECURITY_SALT=oxkwu79632woa07139871298wopz
      - MYSQL_URL=mariadb
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root

  data-mariadb:
    image: busybox
    container_name: mariadb-data

  mariadb:
    image: mariadb:5.5
    container_name: mariadb
    volumes_from:
       - data-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=appusr
      - MYSQL_PASSWORD=AppUsr1
      - MYSQL_DATABASE=vms_db
      - TZ="Asia/Tokyo"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    restart: always
    links:
      - mariadb:mariadb
    ports:
      - "8080:80"

